title: Your Site Title
description: Your site description
baseurl: ""
url: ""

author:
  name: Your Name
  email: your.email@example.com

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/